---
extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc: ~
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

processors: ~

exporters:
  prometheusremotewrite:
    endpoint: "http://mimir:8080/api/v1/push"
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: local
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
