---
extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc: null
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

processors:
  attributes:
    actions:
      - action: insert
        key: event_domain
        from_attribute: event.domain
      - action: insert
        key: loki.attribute.labels
        value: event_domain
  resource:
    attributes:
      - action: insert
        key: service_name
        from_attribute: service.name
      - action: insert
        key: service_namespace
        from_attribute: service.namespace
      - action: insert
        key: loki.resource.labels
        value: service_name, service_namespace

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: http://mimir:8080/api/v1/push
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: local

service:
  extensions:
    - zpages
  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - resource
        - attributes
      exporters:
        - loki
    metrics:
      receivers:
        - otlp
      processors: []
      exporters:
        - prometheusremotewrite
    traces:
      receivers:
        - otlp
      processors: []
      exporters:
        - otlp
