---
extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc: null
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  otlphttp/loki:
    endpoint: http://loki/otlp
    tls:
      insecure: true

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: http://mimir:8080/api/v1/push
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: local

service:
  extensions:
    - zpages
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp/loki]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
