---
extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: ["*"]
          allowed_headers: ["*"]

processors:
  batch: ~
  deltatocumulative: ~

exporters:
  otlp:
    endpoint: otel-lgtm:4317
    tls:
      insecure: true

  clickhouse:
    endpoint: tcp://clickhouse-server:9000
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_tables:
      gauge:
        name: otel_metrics_gauge
      sum:
        name: otel_metrics_sum
      summary:
        name: otel_metrics_summary
      histogram:
        name: otel_metrics_histogram
      exponential_histogram:
        name: otel_metrics_exp_histogram

service:
  extensions:
    - zpages
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, clickhouse]
    metrics:
      receivers: [otlp]
      processors: [deltatocumulative, batch]
      exporters: [otlp, clickhouse]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, clickhouse]
    profiles:
      receivers: [otlp]
      exporters: [otlp]
