---
extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  otlp:
    endpoint: otel-lgtm:4317
    tls:
      insecure: true

service:
  extensions:
    - zpages
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
