---
apiVersion: 1
datasources:
  - access: proxy
    isDefault: true
    name: Mimir
    type: prometheus
    uid: mimir
    url: "http://mimir:8080/prometheus"
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
          urlDisplayLabel: "Query with Tempo"
    secureJsonData:
      httpHeaderValue1: "local"
  - access: proxy
    isDefault: false
    name: Tempo
    type: tempo
    uid: tempo
    url: "http://tempo:3200"
    jsonData:
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: mimir
      spanBar:
        type: Duration
