---
apiVersion: 1
datasources:
  - access: proxy
    isDefault: false
    name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceid":\s*"([A-Fa-f0-9]{0,32})"'
          name: Trace ID
          url: $${__value.raw}
          urlDisplayLabel: Query with Tempo
  - access: proxy
    isDefault: true
    name: Mimir
    type: prometheus
    uid: mimir
    url: http://mimir:8080/prometheus
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
          urlDisplayLabel: Query with Tempo
    secureJsonData:
      httpHeaderValue1: local
  - access: proxy
    isDefault: false
    name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    jsonData:
      lokiSearch:
        datasourceUid: loki
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: mimir
      spanBar:
        type: Duration
      tracesToLogs:
        datasourceUid: loki
        filterBySpanID: true
        filterByTraceID: true
        mapTagNamesEnabled: true
        mappedTags:
          - key: service.name
            value: service_name
          - key: service.namespace
            value: service_namespace
        spanEndTimeShift: 5m
        spanStartTimeShift: -5m
        tags: []
